/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.util.List;

import org.example.cleaning.RecordCleaner;
import org.example.model.PatientRecord;
import org.example.util.JsonFileService;
import org.example.validation.RecordValidator;
import org.example.validation.ValidationIssue;

public class App {
    public String getGreeting() {
        return "Welcome to the Record Validator App!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        String resourcePath = "sample-data/patients-1.json"; 

        if (args.length > 0) {
            resourcePath = args[0]; 
        }
        try {
            JsonFileService fileService = new JsonFileService(); 
            List<PatientRecord>  records = fileService.loadRecords(resourcePath); 

            RecordValidator validator = new RecordValidator(); 
            RecordCleaner cleaner = new RecordCleaner(); 

            // validate, clean, print results. 
            System.out.println("Records loaded " + records.size());
            System.out.println();
            
            records.forEach(record -> {
                PatientRecord cleanedRecord = cleaner.clean(record); 
                List<ValidationIssue> issues = validator.validate(record, cleanedRecord); 
                System.out.println("Initial: " + record.toString());
                System.out.println("Cleaned: " + cleanedRecord.toString());
                if (!issues.isEmpty()) {
                    System.out.println("issues found: ");
                    for (ValidationIssue issue : issues) {
                        System.out.println(issue);
                    }
                }
                System.out.println();
                System.out.println("--------");
                System.out.println();
            });
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
            System.err.println("Make sure the file exists in app/src/main/resources/" + resourcePath);
            System.exit(1); // close with error 
        }
        // System.out.println("Done! Thanks for using the Patient Record Validator.");
        System.out.println("Validation complete. Exiting.");
    }
}
