/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.util.List;

import org.example.cleaning.RecordCleaner;
import org.example.model.PatientRecord;
import org.example.validation.RecordValidator;
import org.example.validation.ValidationIssue;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;; 


public class App {
    public String getGreeting() {
        return "Welcome to the Record Validator App!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        ObjectMapper mapper = new ObjectMapper(); 

        List<PatientRecord> records = mapper.readValue(new File("sample-data/patients-1.json"), new TypeReference<List<PatientRecord>>() {}); 

        RecordCleaner cleaner = new RecordCleaner(); 
        RecordValidator validator = new RecordValidator(); 

        //test the cleaner 
        // System.out.println("Cursed patientId " + records.get(2).patientId);
        // System.out.println("Cleaned patientId " + cleaner.clean(records.get(2)).patientId);

        System.out.println("Records loaded " + records.size());

        for (PatientRecord record : records) {
            System.out.println();
            System.out.println(record);
            System.out.println("Record for " +  record.patientId);
            List<ValidationIssue> issues = validator.validate(record); 
            if (!issues.isEmpty()) {
                System.out.println("issues found: ");
                for (ValidationIssue issue : issues) {
                    System.out.println(issue);
                }
            }
            PatientRecord cleanedRecord = cleaner.clean(record); 
            System.out.println("Initial: " + record.toString());
            System.out.println("Cleaned: " + cleanedRecord.toString());
            System.out.println();
        }
    }
}
