/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.example.model.PatientRecord;

import java.util.List;
import java.io.File;; 


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        ObjectMapper mapper = new ObjectMapper(); 

        List<PatientRecord> records = mapper.readValue(new File("sample-data/patients-1.json"), new TypeReference<List<PatientRecord>>() {});

        System.out.println("Records loaded " + records.size());

        for (PatientRecord record : records) {
            System.out.println(record);
        }
    }
}
